/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { SegmentDto } from '../models';
/**
 * DeviceBlocksConditionApi - axios parameter creator
 * @export
 */
export const DeviceBlocksConditionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceConditionControllerGetSegments: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/device/block/condition/segments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeviceBlocksConditionApi - functional programming interface
 * @export
 */
export const DeviceBlocksConditionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceConditionControllerGetSegments(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<SegmentDto>>>> {
            const localVarAxiosArgs = await DeviceBlocksConditionApiAxiosParamCreator(configuration).deviceConditionControllerGetSegments(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DeviceBlocksConditionApi - factory interface
 * @export
 */
export const DeviceBlocksConditionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceConditionControllerGetSegments(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<SegmentDto>>> {
            return DeviceBlocksConditionApiFp(configuration).deviceConditionControllerGetSegments(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeviceBlocksConditionApi - object-oriented interface
 * @export
 * @class DeviceBlocksConditionApi
 * @extends {BaseAPI}
 */
export class DeviceBlocksConditionApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceBlocksConditionApi
     */
    public async deviceConditionControllerGetSegments(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<SegmentDto>>> {
        return DeviceBlocksConditionApiFp(this.configuration).deviceConditionControllerGetSegments(options).then((request) => request(this.axios, this.basePath));
    }
}
