/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { OutputDto } from '../models';
/**
 * DeviceBlocksOutputApi - axios parameter creator
 * @export
 */
export const DeviceBlocksOutputApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {OutputDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceOutPutControllerAddOrUpdateOutput: async (body: OutputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling deviceOutPutControllerAddOrUpdateOutput.');
            }
            const localVarPath = `/device/block/output`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {OutputDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceOutPutControllerRemoveOutput: async (body: OutputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling deviceOutPutControllerRemoveOutput.');
            }
            const localVarPath = `/device/block/output/update-active-status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeviceBlocksOutputApi - functional programming interface
 * @export
 */
export const DeviceBlocksOutputApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {OutputDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceOutPutControllerAddOrUpdateOutput(body: OutputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await DeviceBlocksOutputApiAxiosParamCreator(configuration).deviceOutPutControllerAddOrUpdateOutput(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {OutputDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceOutPutControllerRemoveOutput(body: OutputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await DeviceBlocksOutputApiAxiosParamCreator(configuration).deviceOutPutControllerRemoveOutput(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DeviceBlocksOutputApi - factory interface
 * @export
 */
export const DeviceBlocksOutputApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {OutputDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceOutPutControllerAddOrUpdateOutput(body: OutputDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return DeviceBlocksOutputApiFp(configuration).deviceOutPutControllerAddOrUpdateOutput(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OutputDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceOutPutControllerRemoveOutput(body: OutputDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return DeviceBlocksOutputApiFp(configuration).deviceOutPutControllerRemoveOutput(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeviceBlocksOutputApi - object-oriented interface
 * @export
 * @class DeviceBlocksOutputApi
 * @extends {BaseAPI}
 */
export class DeviceBlocksOutputApi extends BaseAPI {
    /**
     * 
     * @param {OutputDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceBlocksOutputApi
     */
    public async deviceOutPutControllerAddOrUpdateOutput(body: OutputDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return DeviceBlocksOutputApiFp(this.configuration).deviceOutPutControllerAddOrUpdateOutput(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {OutputDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceBlocksOutputApi
     */
    public async deviceOutPutControllerRemoveOutput(body: OutputDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return DeviceBlocksOutputApiFp(this.configuration).deviceOutPutControllerRemoveOutput(body, options).then((request) => request(this.axios, this.basePath));
    }
}
