/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ActionSourceDto
 */
export interface ActionSourceDto {
    /**
     * 
     * @type {string}
     * @memberof ActionSourceDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActionSourceDto
     */
    value: ActionSourceDtoValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ActionSourceDtoValueEnum {
    Mqtt = 'mqtt',
    Tcp = 'tcp',
    Udp = 'udp'
}

