/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FlowModel } from './flow-model';
/**
 * 
 * @export
 * @interface ActionModel
 */
export interface ActionModel {
    /**
     * 
     * @type {string}
     * @memberof ActionModel
     */
    actionId: string;
    /**
     * 
     * @type {string}
     * @memberof ActionModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActionModel
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof ActionModel
     */
    isExternal: boolean;
    /**
     * 
     * @type {Array<FlowModel>}
     * @memberof ActionModel
     */
    flows: Array<FlowModel>;
    /**
     * 
     * @type {boolean}
     * @memberof ActionModel
     */
    status: boolean;
    /**
     * 
     * @type {string}
     * @memberof ActionModel
     */
    externalUrl?: string;
}
