/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data } from './data';
import { Position } from './position';
/**
 * 
 * @export
 * @interface BoardNodeDto
 */
export interface BoardNodeDto {
    /**
     * 
     * @type {number}
     * @memberof BoardNodeDto
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof BoardNodeDto
     */
    height: number;
    /**
     * 
     * @type {string}
     * @memberof BoardNodeDto
     */
    id: string;
    /**
     * 
     * @type {Data}
     * @memberof BoardNodeDto
     */
    data: Data;
    /**
     * 
     * @type {string}
     * @memberof BoardNodeDto
     */
    type: BoardNodeDtoTypeEnum;
    /**
     * 
     * @type {Position}
     * @memberof BoardNodeDto
     */
    position: Position;
    /**
     * 
     * @type {boolean}
     * @memberof BoardNodeDto
     */
    draggable: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BoardNodeDto
     */
    deletable: boolean;
    /**
     * 
     * @type {Position}
     * @memberof BoardNodeDto
     */
    positionAbsolute: Position;
}

/**
    * @export
    * @enum {string}
    */
export enum BoardNodeDtoTypeEnum {
    Root = 'root',
    Condition = 'condition',
    Logic = 'logic',
    Action = 'action',
    Output = 'output',
    StateSetter = 'state-setter',
    Data = 'data'
}

