/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CloudFunctionInputParameterDto } from './cloud-function-input-parameter-dto';
/**
 * 
 * @export
 * @interface CloudFunction
 */
export interface CloudFunction {
    /**
     * 
     * @type {string}
     * @memberof CloudFunction
     */
    cloudFunctionId: string;
    /**
     * 
     * @type {Array<CloudFunctionInputParameterDto>}
     * @memberof CloudFunction
     */
    inputFields: Array<CloudFunctionInputParameterDto>;
}
