/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CloudFunctionVariablesModel } from './cloud-function-variables-model';
/**
 * 
 * @export
 * @interface CloudFunctionModel
 */
export interface CloudFunctionModel {
    /**
     * 
     * @type {string}
     * @memberof CloudFunctionModel
     */
    cloudFunctionId: string;
    /**
     * 
     * @type {string}
     * @memberof CloudFunctionModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CloudFunctionModel
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CloudFunctionModel
     */
    isInReview: string;
    /**
     * 
     * @type {string}
     * @memberof CloudFunctionModel
     */
    isVerified: string;
    /**
     * 
     * @type {Array<CloudFunctionVariablesModel>}
     * @memberof CloudFunctionModel
     */
    inputs?: Array<CloudFunctionVariablesModel>;
    /**
     * 
     * @type {Array<CloudFunctionVariablesModel>}
     * @memberof CloudFunctionModel
     */
    outputs?: Array<CloudFunctionVariablesModel>;
    /**
     * 
     * @type {string}
     * @memberof CloudFunctionModel
     */
    isPublic: string;
}
