/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CloudFunctionInputParameter } from './cloud-function-input-parameter';
/**
 * 
 * @export
 * @interface CloudFunction
 */
export interface CloudFunction {
    /**
     * 
     * @type {Array<CloudFunctionInputParameter>}
     * @memberof CloudFunction
     */
    inputFields: Array<CloudFunctionInputParameter>;
}
