/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CommandDto
 */
export interface CommandDto {
    /**
     * 
     * @type {string}
     * @memberof CommandDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CommandDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CommandDto
     */
    deviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommandDto
     */
    parameterName: string;
    /**
     * 
     * @type {string}
     * @memberof CommandDto
     */
    parameterValue: string;
}
