/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ComparesModel
 */
export interface ComparesModel {
    /**
     * 
     * @type {string}
     * @memberof ComparesModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ComparesModel
     */
    value: ComparesModelValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ComparesModelValueEnum {
    Previous = 'previous',
    Past30 = 'past30',
    Past60 = 'past60',
    Past300 = 'past300',
    CustomValue = 'customValue',
    State = 'state',
    CustomUserInput = 'customUserInput'
}

