/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConditionDto
 */
export interface ConditionDto {
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    segment: ConditionDtoSegmentEnum;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    operation: ConditionDtoOperationEnum;
    /**
     * 
     * @type {number}
     * @memberof ConditionDto
     */
    threshold: number;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    defaultValue: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    compare: ConditionDtoCompareEnum;
    /**
     * 
     * @type {number}
     * @memberof ConditionDto
     */
    customPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof ConditionDto
     */
    customValue?: number;
    /**
     * 
     * @type {string}
     * @memberof ConditionDto
     */
    value?: string;
    /**
     * 
     * @type {number}
     * @memberof ConditionDto
     */
    customUserInput?: number;
    /**
     * 
     * @type {number}
     * @memberof ConditionDto
     */
    customOperationValue?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum ConditionDtoSegmentEnum {
    ItSelf = 'itSelf',
    Same = 'same',
    Against = 'against',
    Custom = 'custom'
}
/**
    * @export
    * @enum {string}
    */
export enum ConditionDtoOperationEnum {
    Equal = 'equal',
    NotEqual = 'notEqual',
    Greater = 'greater',
    Less = 'less',
    EqualGreater = 'equalGreater',
    EqualLess = 'equalLess',
    DiffGreater = 'diffGreater',
    DiffLess = 'diffLess'
}
/**
    * @export
    * @enum {string}
    */
export enum ConditionDtoCompareEnum {
    Previous = 'previous',
    Past30 = 'past30',
    Past60 = 'past60',
    Past300 = 'past300',
    CustomValue = 'customValue',
    State = 'state',
    CustomUserInput = 'customUserInput'
}

