/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CustomFunctionVariablesModel
 */
export interface CustomFunctionVariablesModel {
    /**
     * 
     * @type {string}
     * @memberof CustomFunctionVariablesModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFunctionVariablesModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFunctionVariablesModel
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFunctionVariablesModel
     */
    type: string;
}
