/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CustomFunctionDto
 */
export interface CustomFunctionDto {
    /**
     * 
     * @type {string}
     * @memberof CustomFunctionDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFunctionDto
     */
    description: string;
}
