/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeviceModel } from './device-model';
/**
 * 
 * @export
 * @interface CustomerModel
 */
export interface CustomerModel {
    /**
     * 
     * @type {string}
     * @memberof CustomerModel
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerModel
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerModel
     */
    phone?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerModel
     */
    lastActivity: Date;
    /**
     * 
     * @type {Array<DeviceModel>}
     * @memberof CustomerModel
     */
    devices: Array<DeviceModel>;
}
