/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActionBoardDto } from './action-board-dto';
import { ConditionDto } from './condition-dto';
import { LogicDto } from './logic-dto';
import { OutputDto } from './output-dto';
import { SetterStateDto } from './setter-state-dto';
/**
 * 
 * @export
 * @interface Data
 */
export interface Data {
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    type: DataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    key: string;
    /**
     * 
     * @type {ConditionDto}
     * @memberof Data
     */
    condition?: ConditionDto;
    /**
     * 
     * @type {SetterStateDto}
     * @memberof Data
     */
    setterState?: SetterStateDto;
    /**
     * 
     * @type {LogicDto}
     * @memberof Data
     */
    logic?: LogicDto;
    /**
     * 
     * @type {ActionBoardDto}
     * @memberof Data
     */
    action?: ActionBoardDto;
    /**
     * 
     * @type {OutputDto}
     * @memberof Data
     */
    output?: OutputDto;
}

/**
    * @export
    * @enum {string}
    */
export enum DataTypeEnum {
    Root = 'root',
    Condition = 'condition',
    Logic = 'logic',
    Action = 'action',
    Output = 'output',
    StateSetter = 'state-setter',
    Data = 'data'
}

