/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Column } from './column';
import { DataHubModel } from './data-hub-model';
import { EffectiveData } from './effective-data';
/**
 * 
 * @export
 * @interface DataHubType
 */
export interface DataHubType {
    /**
     * 
     * @type {string}
     * @memberof DataHubType
     */
    query: DataHubTypeQueryEnum;
    /**
     * 
     * @type {string}
     * @memberof DataHubType
     */
    tableId: string;
    /**
     * 
     * @type {DataHubModel}
     * @memberof DataHubType
     */
    data?: DataHubModel;
    /**
     * 
     * @type {Array<EffectiveData>}
     * @memberof DataHubType
     */
    effectiveData?: Array<EffectiveData>;
    /**
     * 
     * @type {Array<Column>}
     * @memberof DataHubType
     */
    toRetrieveColumns?: Array<Column>;
}

/**
    * @export
    * @enum {string}
    */
export enum DataHubTypeQueryEnum {
    Insert = 'insert',
    Find = 'find',
    Remove = 'remove'
}

