/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Column } from './column';
import { EffectiveDataDto } from './effective-data-dto';
/**
 * 
 * @export
 * @interface DataHubDto
 */
export interface DataHubDto {
    /**
     * 
     * @type {string}
     * @memberof DataHubDto
     */
    query: DataHubDtoQueryEnum;
    /**
     * 
     * @type {string}
     * @memberof DataHubDto
     */
    tableId: string;
    /**
     * 
     * @type {Array<EffectiveDataDto>}
     * @memberof DataHubDto
     */
    effectiveData?: Array<EffectiveDataDto>;
    /**
     * 
     * @type {Array<Column>}
     * @memberof DataHubDto
     */
    toRetrieveColumns?: Array<Column>;
}

/**
    * @export
    * @enum {string}
    */
export enum DataHubDtoQueryEnum {
    Insert = 'insert',
    Find = 'find',
    Remove = 'remove'
}

