/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BoardNodeDto } from './board-node-dto';
import { Edge } from './edge';
import { Viewport } from './viewport';
/**
 * 
 * @export
 * @interface DeviceBoardDto
 */
export interface DeviceBoardDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceBoardDto
     */
    deviceId: string;
    /**
     * 
     * @type {Array<BoardNodeDto>}
     * @memberof DeviceBoardDto
     */
    nodes: Array<BoardNodeDto>;
    /**
     * 
     * @type {Array<Edge>}
     * @memberof DeviceBoardDto
     */
    edges: Array<Edge>;
    /**
     * 
     * @type {Viewport}
     * @memberof DeviceBoardDto
     */
    viewport: Viewport;
}
