/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DynamicValueModel
 */
export interface DynamicValueModel {
    /**
     * 
     * @type {string}
     * @memberof DynamicValueModel
     */
    type: DynamicValueModelTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DynamicValueModel
     */
    parentId: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicValueModel
     */
    outputId: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicValueModel
     */
    parentName: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicValueModel
     */
    outputName: string;
}

/**
    * @export
    * @enum {string}
    */
export enum DynamicValueModelTypeEnum {
    Command = 'command',
    CloudFunction = 'cloud-function',
    DataHub = 'data-hub',
    Global = 'global'
}

