/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DynamicValueModel } from './dynamic-value-model';
/**
 * 
 * @export
 * @interface EffectiveData
 */
export interface EffectiveData {
    /**
     * 
     * @type {string}
     * @memberof EffectiveData
     */
    columnName: string;
    /**
     * 
     * @type {string}
     * @memberof EffectiveData
     */
    operator: EffectiveDataOperatorEnum;
    /**
     * 
     * @type {boolean}
     * @memberof EffectiveData
     */
    isValueDynamic: boolean;
    /**
     * 
     * @type {DynamicValueModel}
     * @memberof EffectiveData
     */
    dynamicValue?: DynamicValueModel;
    /**
     * 
     * @type {string}
     * @memberof EffectiveData
     */
    value: string;
}

/**
    * @export
    * @enum {string}
    */
export enum EffectiveDataOperatorEnum {
    Equal = 'equal',
    Greater = 'greater',
    Less = 'less',
    EqualGreater = 'equalGreater',
    EqualLess = 'EqualLess',
    Contain = 'contain'
}

