/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CloudFunctionType } from './cloud-function-type';
import { CommandModel } from './command-model';
import { DataHubType } from './data-hub-type';
/**
 * 
 * @export
 * @interface FlowModel
 */
export interface FlowModel {
    /**
     * 
     * @type {string}
     * @memberof FlowModel
     */
    flowId: string;
    /**
     * 
     * @type {string}
     * @memberof FlowModel
     */
    type: FlowModelTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof FlowModel
     */
    priority: number;
    /**
     * 
     * @type {CloudFunctionType}
     * @memberof FlowModel
     */
    cloudFunction?: CloudFunctionType;
    /**
     * 
     * @type {CommandModel}
     * @memberof FlowModel
     */
    command?: CommandModel;
    /**
     * 
     * @type {DataHubType}
     * @memberof FlowModel
     */
    dataHub?: DataHubType;
}

/**
    * @export
    * @enum {string}
    */
export enum FlowModelTypeEnum {
    Command = 'command',
    CloudFunction = 'cloud-function',
    DataHub = 'data-hub',
    Global = 'global'
}

