/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommandModel } from './command-model';
import { DatabaseType } from './database-type';
import { MarketType } from './market-type';
/**
 * 
 * @export
 * @interface FlowModel
 */
export interface FlowModel {
    /**
     * 
     * @type {string}
     * @memberof FlowModel
     */
    flowId: string;
    /**
     * 
     * @type {string}
     * @memberof FlowModel
     */
    type: FlowModelTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof FlowModel
     */
    priority: number;
    /**
     * 
     * @type {MarketType}
     * @memberof FlowModel
     */
    market?: MarketType;
    /**
     * 
     * @type {CommandModel}
     * @memberof FlowModel
     */
    command?: CommandModel;
    /**
     * 
     * @type {DatabaseType}
     * @memberof FlowModel
     */
    database?: DatabaseType;
}

/**
    * @export
    * @enum {string}
    */
export enum FlowModelTypeEnum {
    Command = 'command',
    Market = 'market',
    Database = 'database',
    Device = 'device'
}

