/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomSegmentDto } from './custom-segment-dto';
/**
 * 
 * @export
 * @interface GetCustomSegmentList
 */
export interface GetCustomSegmentList {
    /**
     * 
     * @type {Array<CustomSegmentDto>}
     * @memberof GetCustomSegmentList
     */
    data?: Array<CustomSegmentDto>;
    /**
     * 
     * @type {boolean}
     * @memberof GetCustomSegmentList
     */
    more?: boolean;
}
