/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CloudFunctionModel } from './cloud-function-model';
/**
 * 
 * @export
 * @interface GetFunctionsList
 */
export interface GetFunctionsList {
    /**
     * 
     * @type {Array<CloudFunctionModel>}
     * @memberof GetFunctionsList
     */
    data?: Array<CloudFunctionModel>;
    /**
     * 
     * @type {boolean}
     * @memberof GetFunctionsList
     */
    more?: boolean;
}
