/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerModel } from './customer-model';
/**
 * 
 * @export
 * @interface GetAllCustomersByOrgId
 */
export interface GetAllCustomersByOrgId {
    /**
     * 
     * @type {Array<CustomerModel>}
     * @memberof GetAllCustomersByOrgId
     */
    data?: Array<CustomerModel>;
    /**
     * 
     * @type {boolean}
     * @memberof GetAllCustomersByOrgId
     */
    more?: boolean;
}
