/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SegmentDto } from './segment-dto';
/**
 * 
 * @export
 * @interface GetSegments
 */
export interface GetSegments {
    /**
     * 
     * @type {Array<SegmentDto>}
     * @memberof GetSegments
     */
    data?: Array<SegmentDto>;
    /**
     * 
     * @type {boolean}
     * @memberof GetSegments
     */
    more?: boolean;
}
