/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TableDataModel } from './table-data-model';
/**
 * 
 * @export
 * @interface GetTableData
 */
export interface GetTableData {
    /**
     * 
     * @type {Array<TableDataModel>}
     * @memberof GetTableData
     */
    data?: Array<TableDataModel>;
    /**
     * 
     * @type {boolean}
     * @memberof GetTableData
     */
    more?: boolean;
}
