/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BoardNodeDto } from './board-node-dto';
/**
 * 
 * @export
 * @interface GetOutputs
 */
export interface GetOutputs {
    /**
     * 
     * @type {Array<BoardNodeDto>}
     * @memberof GetOutputs
     */
    data?: Array<BoardNodeDto>;
    /**
     * 
     * @type {boolean}
     * @memberof GetOutputs
     */
    more?: boolean;
}
