/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommandModel } from './command-model';
/**
 * 
 * @export
 * @interface GetCommandsList
 */
export interface GetCommandsList {
    /**
     * 
     * @type {Array<CommandModel>}
     * @memberof GetCommandsList
     */
    data?: Array<CommandModel>;
    /**
     * 
     * @type {boolean}
     * @memberof GetCommandsList
     */
    more?: boolean;
}
