/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QueryModel } from './query-model';
/**
 * 
 * @export
 * @interface GetQueries
 */
export interface GetQueries {
    /**
     * 
     * @type {Array<QueryModel>}
     * @memberof GetQueries
     */
    data?: Array<QueryModel>;
    /**
     * 
     * @type {boolean}
     * @memberof GetQueries
     */
    more?: boolean;
}
