/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActionTypeDto } from './action-type-dto';
/**
 * 
 * @export
 * @interface GetActionType
 */
export interface GetActionType {
    /**
     * 
     * @type {Array<ActionTypeDto>}
     * @memberof GetActionType
     */
    data?: Array<ActionTypeDto>;
    /**
     * 
     * @type {boolean}
     * @memberof GetActionType
     */
    more?: boolean;
}
