/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperationDto } from './operation-dto';
/**
 * 
 * @export
 * @interface GetOperations
 */
export interface GetOperations {
    /**
     * 
     * @type {Array<OperationDto>}
     * @memberof GetOperations
     */
    data?: Array<OperationDto>;
    /**
     * 
     * @type {boolean}
     * @memberof GetOperations
     */
    more?: boolean;
}
