/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FlowModel } from './flow-model';
/**
 * 
 * @export
 * @interface GetFlows
 */
export interface GetFlows {
    /**
     * 
     * @type {Array<FlowModel>}
     * @memberof GetFlows
     */
    data?: Array<FlowModel>;
    /**
     * 
     * @type {boolean}
     * @memberof GetFlows
     */
    more?: boolean;
}
