/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DynamicValueDto } from './dynamic-value-dto';
/**
 * 
 * @export
 * @interface MarketInputParameter
 */
export interface MarketInputParameter {
    /**
     * 
     * @type {string}
     * @memberof MarketInputParameter
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarketInputParameter
     */
    isValueDynamic: boolean;
    /**
     * 
     * @type {DynamicValueDto}
     * @memberof MarketInputParameter
     */
    dynamicValue: DynamicValueDto;
    /**
     * 
     * @type {string}
     * @memberof MarketInputParameter
     */
    value: string;
}
