/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MarketInputParameter } from './market-input-parameter';
/**
 * 
 * @export
 * @interface MarketType
 */
export interface MarketType {
    /**
     * 
     * @type {string}
     * @memberof MarketType
     */
    id: string;
    /**
     * 
     * @type {Array<MarketInputParameter>}
     * @memberof MarketType
     */
    inputFields: Array<MarketInputParameter>;
}
