/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Column } from './column';
/**
 * 
 * @export
 * @interface NewColumnDto
 */
export interface NewColumnDto {
    /**
     * 
     * @type {Array<Column>}
     * @memberof NewColumnDto
     */
    columns: Array<Column>;
}
