/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OperationDto
 */
export interface OperationDto {
    /**
     * 
     * @type {string}
     * @memberof OperationDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OperationDto
     */
    value: OperationDtoValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum OperationDtoValueEnum {
    Equal = 'equal',
    Greater = 'greater',
    Less = 'less',
    EqualGreater = 'equalGreater',
    EqualLess = 'equalLess',
    DiffGreater = 'diffGreater',
    DiffLess = 'diffLess'
}

