/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface QueryModel
 */
export interface QueryModel {
    /**
     * 
     * @type {string}
     * @memberof QueryModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof QueryModel
     */
    value: QueryModelValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum QueryModelValueEnum {
    Insert = 'insert',
    Find = 'find',
    Remove = 'remove'
}

