/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SegmentDto
 */
export interface SegmentDto {
    /**
     * 
     * @type {string}
     * @memberof SegmentDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SegmentDto
     */
    value: SegmentDtoValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SegmentDtoValueEnum {
    ItSelf = 'itSelf',
    Same = 'same',
    Against = 'against',
    Custom = 'custom'
}

