/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SetterStateDto
 */
export interface SetterStateDto {
    /**
     * 
     * @type {string}
     * @memberof SetterStateDto
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof SetterStateDto
     */
    value: string;
}
