/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetaData } from './meta-data';
/**
 * 
 * @export
 * @interface SimulateResponseModel
 */
export interface SimulateResponseModel {
    /**
     * 
     * @type {MetaData}
     * @memberof SimulateResponseModel
     */
    metadata: MetaData;
    /**
     * 
     * @type {string}
     * @memberof SimulateResponseModel
     */
    actionType: SimulateResponseModelActionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SimulateResponseModel
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof SimulateResponseModel
     */
    block: string;
    /**
     * 
     * @type {string}
     * @memberof SimulateResponseModel
     */
    title: string;
    /**
     * 
     * @type {any}
     * @memberof SimulateResponseModel
     */
    data: any;
    /**
     * 
     * @type {number}
     * @memberof SimulateResponseModel
     */
    timestamp: number;
    /**
     * 
     * @type {Date}
     * @memberof SimulateResponseModel
     */
    createdAt: Date;
}

/**
    * @export
    * @enum {string}
    */
export enum SimulateResponseModelActionTypeEnum {
    Root = 'root',
    Condition = 'condition',
    Logic = 'logic',
    Action = 'action',
    Output = 'output',
    StateSetter = 'state-setter',
    Data = 'data'
}

