/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SimulateOutputDto } from './simulate-output-dto';
/**
 * 
 * @export
 * @interface SimulateDto
 */
export interface SimulateDto {
    /**
     * 
     * @type {string}
     * @memberof SimulateDto
     */
    deviceId: string;
    /**
     * 
     * @type {Array<SimulateOutputDto>}
     * @memberof SimulateDto
     */
    data: Array<SimulateOutputDto>;
}
