/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SubDeviceModel
 */
export interface SubDeviceModel {
    /**
     * 
     * @type {string}
     * @memberof SubDeviceModel
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof SubDeviceModel
     */
    subDeviceId: string;
    /**
     * 
     * @type {string}
     * @memberof SubDeviceModel
     */
    deviceName: string;
    /**
     * 
     * @type {string}
     * @memberof SubDeviceModel
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof SubDeviceModel
     */
    customerId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubDeviceModel
     */
    status: boolean;
}
