/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetaData } from './meta-data';
/**
 * 
 * @export
 * @interface SubDeviceHistoricalDataModel
 */
export interface SubDeviceHistoricalDataModel {
    /**
     * 
     * @type {MetaData}
     * @memberof SubDeviceHistoricalDataModel
     */
    metadata: MetaData;
    /**
     * 
     * @type {any}
     * @memberof SubDeviceHistoricalDataModel
     */
    outputs: any;
    /**
     * 
     * @type {string}
     * @memberof SubDeviceHistoricalDataModel
     */
    framework: string;
    /**
     * 
     * @type {string}
     * @memberof SubDeviceHistoricalDataModel
     */
    signalStrength: string;
    /**
     * 
     * @type {string}
     * @memberof SubDeviceHistoricalDataModel
     */
    ipAddress: string;
    /**
     * 
     * @type {number}
     * @memberof SubDeviceHistoricalDataModel
     */
    timestamp: number;
}
