/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TableDto
 */
export interface TableDto {
    /**
     * 
     * @type {string}
     * @memberof TableDto
     */
    tableName: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof TableDto
     */
    columns: { [key: string]: string; };
}
