/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Column } from './column';
/**
 * 
 * @export
 * @interface Table
 */
export interface Table {
    /**
     * 
     * @type {string}
     * @memberof Table
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof Table
     */
    tableId: string;
    /**
     * 
     * @type {string}
     * @memberof Table
     */
    name: string;
    /**
     * 
     * @type {Array<Column>}
     * @memberof Table
     */
    columns: Array<Column>;
    /**
     * 
     * @type {string}
     * @memberof Table
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof Table
     */
    columnLimit: number;
}
