/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ColumnModel } from './column-model';
/**
 * 
 * @export
 * @interface TableModel
 */
export interface TableModel {
    /**
     * 
     * @type {string}
     * @memberof TableModel
     */
    tableId: string;
    /**
     * 
     * @type {string}
     * @memberof TableModel
     */
    tableName: string;
    /**
     * 
     * @type {string}
     * @memberof TableModel
     */
    description?: string;
    /**
     * 
     * @type {Array<ColumnModel>}
     * @memberof TableModel
     */
    columns: Array<ColumnModel>;
}
