/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateCommandDto
 */
export interface UpdateCommandDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCommandDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommandDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommandDto
     */
    deviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommandDto
     */
    parameterName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCommandDto
     */
    parameterValue?: string;
}
