/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateDeviceDto
 */
export interface UpdateDeviceDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateDeviceDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDeviceDto
     */
    description?: string;
}
