/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserProfileModel
 */
export interface UserProfileModel {
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    firstname: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    status: UserProfileModelStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModel
     */
    subscriptionType: UserProfileModelSubscriptionTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UserProfileModelStatusEnum {
    Active = 'active',
    Inactive = 'inactive',
    Suspended = 'suspended'
}
/**
    * @export
    * @enum {string}
    */
export enum UserProfileModelSubscriptionTypeEnum {
    Free = 'free',
    Pro = 'Pro',
    Enterprise = 'Enterprise'
}

