/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Viewport
 */
export interface Viewport {
    /**
     * 
     * @type {number}
     * @memberof Viewport
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof Viewport
     */
    y: number;
    /**
     * 
     * @type {number}
     * @memberof Viewport
     */
    zoom: number;
}
