/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WorkspaceDetail } from './workspace-detail';
/**
 * 
 * @export
 * @interface WorkspaceModel
 */
export interface WorkspaceModel {
    /**
     * 
     * @type {number}
     * @memberof WorkspaceModel
     */
    workspaceLimit: number;
    /**
     * 
     * @type {Array<WorkspaceDetail>}
     * @memberof WorkspaceModel
     */
    workspaces: Array<WorkspaceDetail>;
}
